import { type ReactNode, useEffect, useRef, useState } from "react";
import { ArrowRight, BadgeCheck, Brain, Check, ChevronDown, CircleCheck, Eye, Gauge, Layers3, Lightbulb, LockKeyhole, MessageSquareText, ShieldCheck, Sparkles, Target, Video, X } from "lucide-react";

import tuMenteEnGPTCover from "@/assets/tu-mente-en-gpt-cover-v2.png.asset.json";
import tuSegundoCerebroCover from "@/assets/tu-segundo-cerebro-cover-v2.png.asset.json";
import tuGemeloDigitalCover from "@/assets/tu-gemelo-digital-cover-v2.png.asset.json";
import elEspejoDigitalCover from "@/assets/el-espejo-digital-cover-v2.png.asset.json";
import depoimento10 from "@/assets/depoimento-10.png.asset.json";
import depoimento11 from "@/assets/depoimento-11.png.asset.json";
import depoimento12 from "@/assets/depoimento-12.png.asset.json";
import depoimento13 from "@/assets/depoimento-13.png.asset.json";
import depoimento14 from "@/assets/depoimento-14.png.asset.json";
import depoimento15 from "@/assets/depoimento-15.png.asset.json";
import comboCover from "@/assets/combo-mente-expandida-novo.png.asset.json";
import metodoNovo39 from "@/assets/metodo-novo-39.png.asset.json";
import metodoNovo40 from "@/assets/metodo-novo-40.png.asset.json";
import metodoNovo41 from "@/assets/metodo-novo-41.png.asset.json";
import metodoNovo42 from "@/assets/metodo-novo-42.png.asset.json";
import metodoNovo43 from "@/assets/metodo-novo-43.png.asset.json";
import metodoNovo44 from "@/assets/metodo-novo-44.png.asset.json";

const pilarImagens = [metodoNovo39, metodoNovo40, metodoNovo41, metodoNovo42, metodoNovo43, metodoNovo44];
const depoimentos = [depoimento10, depoimento11, depoimento12, depoimento13, depoimento14, depoimento15];
const guiasEsteira = [tuMenteEnGPTCover, elEspejoDigitalCover, tuSegundoCerebroCover, tuGemeloDigitalCover];
const faixaItens = ["EXPANDED MIND METHOD™", "MAIN GUIDE + FREE BONUSES", "ONE-TIME PAYMENT", "INSTANT ACCESS", "7-DAY GUARANTEE", "YOUR AI, YOUR WAY"];
const typewriterWords = ["CREATE.", "LEARN.", "PRODUCE.", "ACHIEVE."];

function TypewriterWord() {
  const [wordIndex, setWordIndex] = useState(0);
  const [charCount, setCharCount] = useState(0);
  const [deleting, setDeleting] = useState(false);
  useEffect(() => {
    const word = typewriterWords[wordIndex]!;
    const delay = !deleting ? (charCount < word.length ? 110 : 1700) : (charCount > 0 ? 60 : 350);
    const timer = setTimeout(() => {
      if (!deleting) {
        if (charCount < word.length) setCharCount(charCount + 1); else setDeleting(true);
      } else if (charCount > 0) setCharCount(charCount - 1);
      else { setDeleting(false); setWordIndex((wordIndex + 1) % typewriterWords.length); }
    }, delay);
    return () => clearTimeout(timer);
  }, [charCount, deleting, wordIndex]);
  return <span className="relative inline-flex items-baseline"><span className="opacity-0" aria-hidden>ACHIEVE.</span><span className="upsell-text-gradient-gold absolute left-1/2 top-0 -translate-x-1/2 whitespace-nowrap" aria-hidden>{typewriterWords[wordIndex]!.slice(0, charCount)}<span className="ml-1 inline-block h-[0.85em] w-[3px] animate-pulse bg-upsell-gold align-baseline" /></span></span>;
}

const problemas = [
  "You open the chat and start from scratch. Every day. In every conversation.",
  "You lose minutes (and energy) explaining again who you are, what you do, and what you want to achieve.",
  "You get generic answers that could have been written for anyone — except you.",
  "You have great ideas, but they stay in your head because you can't organize, prioritize, or execute them.",
  "You know content sells, but you don't want to spend your life recording yourself on camera.",
  "All your knowledge is scattered across notes, chats, and ideas… with no system turning it into results.",
];
const beneficiosMente = ["Teach AI who you are and how you work", "Set your tone of voice and preferences", "Organize information about your products and audience", "Turn your knowledge into a searchable knowledge base", "Get responses that are more consistent with your context", "Reduce corrections, repetition, and rework", "Create content without losing your personality", "Have an intelligence ready to start from the right place"];
const beneficiosEspejo = ["Recurring patterns of thought", "Recurring ways of making decisions", "Strengths and abilities you may be underestimating", "Possible beliefs and blocks reflected in your words", "Topics that frequently occupy your attention", "Opportunities that may be right in front of you without being recognized", "Changes that have taken place throughout your journey", "A true “manual for your mind”"];
const comboItens = [
  { nome: "Your Mind in GPT", etiqueta: "Guide 1", desc: "Personalize ChatGPT with your context" },
  { nome: "Your Second Brain", etiqueta: "Guide 2", desc: "Think with greater clarity inside ChatGPT" },
  { nome: "Your Digital Twin", etiqueta: "Guide 3", desc: "Turn ideas into digital presence" },
  { nome: "The Digital Mirror", etiqueta: "Guide 4", desc: "Guided reflection with ChatGPT support" },
];
const pilares = [
  { step: "01", name: "Your Mind in GPT", tag: "KNOWS", icon: Brain, title: "Your ChatGPT feels generic because it doesn't know you yet.", text: "Learn, step by step and without programming, how to create a GPT with your context, personality, tone of voice, and goals — so you get much more aligned responses without having to explain everything again.", resultado: "RESULT: YOUR DIGITAL MIND, BUILT." },
  { step: "02", name: "The Digital Mirror", tag: "BONUS", icon: Eye, title: "What if AI had already noticed something about you that you haven't noticed yet?", text: "Use guided prompts to observe patterns in your conversations, recognize strengths, possible blocks, decision-making styles, and opportunities that may be going unnoticed.", resultado: "RESULT: A NEW PERSPECTIVE ON YOURSELF." },
  { step: "03", name: "Your Second Brain", tag: "THINKS", icon: Lightbulb, title: "Does your mind have too many ideas and not enough clarity?", text: "Use ready-to-copy master commands inside ChatGPT to organize thoughts, develop ideas, analyze decisions, find blind spots, and turn goals into concrete plans.", resultado: "RESULT: AN INTELLIGENCE THAT THINKS WITH YOU." },
  { step: "04", name: "Your Digital Twin", tag: "MULTIPLIES", icon: Video, title: "Create once. Show up many times.", text: "Learn a fast and surprisingly easy process for turning text into videos with an avatar and voice — even if you don't like recording, have little time, or have never edited a video.", resultado: "RESULT: YOUR IDEAS GAIN VOICE, IMAGE, AND PRESENCE." },
];
const resultados = [
  { icon: Brain, title: "An AI that knows you", text: "No more generic answers: AI understands your context and responds in your mental language." },
  { icon: Lightbulb, title: "Ideas that multiply", text: "One idea becomes angles, formats, and opportunities you might not have seen on your own." },
  { icon: Target, title: "Better-informed decisions", text: "Analyze risks, priorities, and blind spots before you act. Less uncertainty, more progress." },
  { icon: Layers3, title: "An organized mind", text: "Scattered information becomes clear structures, ready to execute." },
  { icon: MessageSquareText, title: "Frictionless content", text: "From thought to script, post, or message: publish more with less effort." },
  { icon: Video, title: "Videos without recording yourself", text: "Your avatar and voice work for you. Multiply your presence without multiplying your time." },
  { icon: Gauge, title: "10x faster execution", text: "The distance between thinking of an idea and launching it drops to minutes, not weeks." },
  { icon: Eye, title: "See what others don't", text: "Better questions, clear patterns, and opportunities that previously went unnoticed." },
];
const recursos = ["Master Profile", "Master Prompt", "High-Value Commands", "Decision System", "Action Plans", "Risk Analysis", "AI Avatar", "AI Voice", "Video Scripts", "Reflection Prompts", "Strengths Map", "Growth Questions"];
const perguntas = [["Do I need to know how to code?", "No. The method was designed to be applied without programming or advanced prompt expertise. If you can write a message, you can apply it."], ["Do I need experience with artificial intelligence?", "No. You can start from zero and move forward by following the step-by-step process in each guide."], ["Does the method work with ChatGPT?", "Yes. Your Mind in GPT and Your Second Brain were designed to use ChatGPT as the foundation for the work, and the principles apply to any text-based AI."], ["Can I use it in my business?", "Yes. The system helps you organize ideas, create content, analyze decisions, plan projects, and turn knowledge into execution."], ["Do I need to know how to edit videos?", "You don't need advanced editing skills. Your Digital Twin simplifies production with artificial intelligence tools."], ["How do I get access?", "After payment is confirmed, access is delivered digitally through the purchase platform. You can get started within minutes."], ["Is it a one-time payment?", "Yes, this offer is a one-time payment. Final terms are confirmed at the secure checkout before you complete your purchase."], ["How does the 7-day guarantee work?", "You have 7 days to experience the method from the inside. If you decide it's not for you, request the guarantee within the applicable period according to the purchase platform's terms."]];

function MatrixRain() {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current; if (!canvas) return; const ctx = canvas.getContext("2d"); if (!ctx) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    let raf = 0, last = 0; const fontSize = 16; const chars = "アイウエオカキクケコサシスセソ01<>[]{}#$%&"; let drops: number[] = [];
    const resize = () => { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; drops = Array.from({ length: Math.ceil(canvas.width / fontSize) }, () => Math.floor(Math.random() * -50)); };
    resize(); window.addEventListener("resize", resize);
    const draw = (t: number) => { raf = requestAnimationFrame(draw); if (t - last < 78) return; last = t; ctx.fillStyle = "rgba(6, 10, 24, 0.2)"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.font = `${fontSize}px "Share Tech Mono", monospace`; drops.forEach((y, i) => { const ch = chars[Math.floor(Math.random() * chars.length)] ?? "0"; ctx.fillStyle = Math.random() > 0.975 ? "rgba(191, 219, 254, 0.5)" : "rgba(96, 165, 250, 0.22)"; ctx.fillText(ch, i * fontSize, y * fontSize); drops[i] = y * fontSize > canvas.height && Math.random() > 0.975 ? 0 : y + 1; }); };
    raf = requestAnimationFrame(draw); return () => { cancelAnimationFrame(raf); window.removeEventListener("resize", resize); };
  }, []);
  return <canvas ref={ref} aria-hidden className="upsell-matrix pointer-events-none absolute inset-0 h-full w-full opacity-60" />;
}
function SectionTitle({ label, title, light = false, children }: { label: string; title: ReactNode; light?: boolean; children?: ReactNode }) { return <div className="mx-auto max-w-3xl text-center"><div className={`upsell-eyebrow mb-4 text-xs tracking-[0.28em] uppercase ${light ? "text-upsell-light-blue" : "text-upsell-blue"}`}>{label}</div><h2 className={`text-3xl font-bold tracking-[-0.01em] sm:text-4xl md:text-5xl ${light ? "text-upsell-light-text" : "text-white"}`}>{title}</h2>{children ? <div className={`mt-5 text-base leading-7 sm:text-lg ${light ? "text-upsell-light-muted" : "text-upsell-text-muted"}`}>{children}</div> : null}</div>; }
function CTA({ children = "I WANT THE EXPANDED MIND COMBO", href = "#offer" }: { children?: ReactNode; href?: string }) { return <a href={href} className="upsell-cta inline-flex w-full max-w-xl items-center justify-center gap-2 whitespace-nowrap rounded-2xl px-4 py-5 text-center text-xs tracking-wide text-white uppercase sm:gap-3 sm:px-6 sm:text-base">{children}<ArrowRight className="h-5 w-5 shrink-0" /></a>; }
function CoverCard({ cover, name }: { cover: { url: string }; name: string }) { return <div className="w-[220px] shrink-0 overflow-hidden rounded-[24px] p-1 sm:w-[280px]"><img src={cover.url} alt={`Cover ${name}`} className="h-[240px] w-full rounded-[18px] object-cover sm:h-[290px]" /></div>; }
function TestimonialCard({ image, index }: { image: { url: string }; index: number }) { return <div className="w-[240px] shrink-0 overflow-hidden rounded-[20px] p-1 sm:w-[300px]"><img src={image.url} alt={`Customer testimonial ${index + 1}`} className="h-auto w-full rounded-[14px] object-contain" /></div>; }
function GuidesMarquee() { return <div className="upsell-marquee-mask mt-8 overflow-hidden"><div className="upsell-marquee flex w-max items-center gap-5 px-5">{[...guiasEsteira, ...guiasEsteira].map((cover, index) => <div key={`${cover.url}-${index}`} className="w-[220px] shrink-0 overflow-hidden rounded-[24px] border border-white/10 bg-white/[0.035] p-1 shadow-[0_24px_70px_-35px_rgba(96,165,250,0.45)] sm:w-[280px]"><img src={cover.url} alt={`Cover ${index % guiasEsteira.length + 1} of the Expanded Mind Method`} className="aspect-square w-full rounded-[18px] object-cover" /></div>)}</div></div>; }
const compradores = ["Mariana S.", "Carlos P.", "Fernanda L.", "João M.", "Ana Paula R.", "Ricardo T.", "Camila V.", "Diego A.", "Patrícia G."];
function SalesNotifications() { const [current, setCurrent] = useState(0); useEffect(() => { const timer = setInterval(() => setCurrent((value) => (value + 1) % compradores.length), 4200); return () => clearInterval(timer); }, []); return <div className="fixed bottom-4 left-4 z-40 hidden max-w-[320px] rounded-2xl border border-green-400/40 bg-gradient-to-r from-green-700 via-green-600 to-green-700 p-4 shadow-[0_12px_35px_-12px_rgba(34,197,94,0.75)] backdrop-blur-md sm:block"><div className="flex items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/15 text-white"><Check className="h-4 w-4" /></div><div><p className="text-xs leading-5 text-white"><span className="font-bold">{compradores[current]}</span> purchased the <span className="font-bold text-white">Expanded Mind Method Combo</span></p><p className="mt-1 text-[10px] text-white/75">A few minutes ago</p></div></div></div>; }

export function TuGemeloDigitalPage() {
  return <main className="upsell-font overflow-hidden bg-upsell-bg text-upsell-text selection:bg-upsell-blue selection:text-white">
    <div className="border-b border-red-500/40 bg-gradient-to-r from-red-700 via-red-600 to-red-700 px-4 py-2.5 text-center text-[9px] font-bold leading-4 tracking-[0.08em] text-white uppercase sm:text-xs sm:tracking-[0.14em]">🔥 This promotional offer is ending soon!</div>
    <section id="full-offer-top" className="relative overflow-hidden border-b border-white/10 bg-black/25 px-5 py-14 sm:px-6 sm:py-20"><div className="pointer-events-none absolute left-1/2 top-1/2 h-[500px] w-[800px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-upsell-gold/10 blur-[150px]" /><div className="relative mx-auto max-w-5xl text-center"><span className="upsell-eyebrow inline-flex items-center gap-2 rounded-full border border-upsell-gold/30 bg-upsell-gold/10 px-5 py-2 text-xs tracking-[0.18em] text-upsell-gold uppercase"><Sparkles className="h-4 w-4" /> Expanded Mind Method™</span><h1 className="mt-6 text-3xl font-bold tracking-[-0.01em] text-white sm:text-4xl md:text-5xl">The complete Expanded Mind Method<span className="upsell-text-gradient-gold block">All 4 guides in one combo.</span></h1><p className="mx-auto mt-5 max-w-3xl text-base leading-7 text-upsell-text-muted sm:text-lg">You get all four parts of the method to personalize ChatGPT, think with greater clarity, recognize new patterns, and multiply your digital presence.</p><img src={comboCover.url} alt="Complete Expanded Mind Method with all four guides" className="mx-auto mt-9 w-full max-w-[340px] rounded-[28px] object-cover sm:max-w-md" /><div className="mx-auto mt-9 max-w-3xl grid gap-3 text-left sm:grid-cols-2">{comboItens.map(item => <div key={item.nome} className="rounded-2xl border border-white/10 bg-white/[0.045] px-5 py-4"><p className="font-bold text-white">{item.nome} <span className="ml-1 rounded-full bg-upsell-blue/20 px-2 py-0.5 text-[10px] font-bold tracking-wider text-upsell-blue uppercase">{item.etiqueta}</span></p><p className="mt-1 text-xs text-upsell-text-muted">{item.desc}</p></div>)}</div><div className="mt-8 flex justify-center"><CTA href="#combo" /></div></div></section>
    <section className="relative overflow-hidden px-5 pb-12 pt-14 sm:px-6 sm:pb-16 sm:pt-20"><MatrixRain /><div className="pointer-events-none absolute left-1/2 top-0 h-[520px] w-[720px] -translate-x-1/2 rounded-full bg-upsell-blue/15 blur-[140px]" /><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-5xl text-center"><span className="upsell-eyebrow inline-flex items-center gap-2 rounded-full border border-upsell-blue/25 bg-upsell-blue/10 px-4 py-2 text-[11px] tracking-[0.22em] text-upsell-blue uppercase sm:text-xs"><Sparkles className="h-4 w-4" /> Expanded Mind Method™</span><h2 className="mt-7 text-xl font-bold leading-[1.2] tracking-tight text-white sm:text-3xl md:text-4xl">DISCOVER HOW TO UNLOCK THE FULL POWER OF ARTIFICIAL INTELLIGENCE AND TURN IT INTO A TRUE <span className="upsell-text-gradient-blue">RESULTS MACHINE FOR</span><span className="mt-1.5 block text-3xl font-extrabold tracking-wide sm:text-5xl md:text-6xl"><TypewriterWord /></span></h2><GuidesMarquee /><p className="mx-auto mt-8 max-w-3xl text-base leading-7 text-upsell-text-muted sm:text-xl sm:leading-8">Your ChatGPT feels generic because it doesn't know you yet. Learn to build a personalized intelligence with <span className="font-semibold text-white">your context, identity, tone of voice, and goals</span> — and stop explaining everything again in every conversation.</p><p className="mx-auto mt-5 max-w-3xl rounded-2xl border border-upsell-blue/25 bg-upsell-blue/[0.07] px-5 py-4 text-sm leading-6 text-white/80 sm:text-base">No programming, no code, and no complicated configurations. Follow the step-by-step process, copy, adapt, and start building your personalized intelligence.</p><div className="mt-9 flex justify-center"><CTA /></div><div className="mt-5 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs font-semibold text-white/55 sm:text-sm"><span className="flex items-center gap-2"><CircleCheck className="h-4 w-4 text-upsell-success" /> Instant digital access</span><span className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-upsell-success" /> 100% secure payment</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-upsell-success" /> 7-day guarantee</span></div></div></div></section>
    <div className="upsell-marquee-mask border-y border-upsell-blue/30 bg-gradient-to-r from-blue-700 via-upsell-blue to-blue-700 py-3.5"><div className="upsell-marquee flex w-max items-center gap-8 px-4">{[...faixaItens, ...faixaItens, ...faixaItens, ...faixaItens].map((item, index) => <span key={index} className="upsell-eyebrow flex items-center gap-8 whitespace-nowrap text-xs tracking-[0.22em] text-white uppercase sm:text-sm">{item}<span className="text-white/50">◆</span></span>)}</div></div>
    <section className="border-b border-white/10 bg-white/[0.02] px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle label="THE REAL PROBLEM" title={<>AI is already brilliant.<br /><span className="upsell-text-gradient-blue">The problem is that it doesn't know who you are.</span></>}>Every day you use AI without a system, you pay an invisible price: time, clarity, and opportunities. See if any of these statements feels a little too familiar:</SectionTitle><div className="mx-auto mt-8 grid max-w-5xl gap-4 md:grid-cols-2">{problemas.map(problem => <div key={problem} className="group flex items-center gap-4 rounded-2xl border border-red-500/40 bg-gradient-to-r from-red-600/20 to-red-500/[0.07] p-5 text-left shadow-[0_16px_50px_-25px_rgba(239,68,68,0.6)] sm:p-6"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-red-400/50 bg-red-500/25 text-red-300"><X className="h-5 w-5" /></span><p className="text-sm leading-6 font-bold text-red-100 sm:text-base">{problem}</p></div>)}</div><div className="mx-auto mt-10 flex max-w-4xl justify-center"><CTA /></div></div></section>
    <section className="bg-upsell-light px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle light label="THE SYSTEM" title={<>Each guide works on its own.<br /><span className="text-upsell-light-blue">Together, they expand your full potential.</span></>}>You can use each solution separately. When you connect all four, each step complements the next and turns ChatGPT into a more complete system to <span className="font-semibold">know, think, create, and multiply with you.</span></SectionTitle><div className="mt-10 grid gap-5 lg:grid-cols-2">{pilares.map(pilar => { const Icon = pilar.icon; return <article key={pilar.name} className="group relative overflow-hidden rounded-[30px] border border-upsell-light-border bg-upsell-light-surface p-7 text-center shadow-[0_24px_70px_-40px_rgba(30,58,138,0.35)] sm:p-9"><div className="relative flex flex-col items-center"><div className="grid h-14 w-14 place-items-center rounded-2xl border border-upsell-light-blue/25 bg-upsell-light-blue/10 text-upsell-light-blue"><Icon className="h-6 w-6" /></div><div className="upsell-eyebrow mt-5 text-xs tracking-[0.2em] text-upsell-light-blue">{pilar.step} · {pilar.tag}</div><h3 className="mt-2 text-2xl font-bold text-upsell-light-text sm:text-3xl">{pilar.name}</h3><p className="mt-3 text-base font-semibold text-upsell-light-text/80">{pilar.title}</p><p className="mt-3 text-sm leading-7 text-upsell-light-muted sm:text-base">{pilar.text}</p><p className="upsell-eyebrow mt-4 text-[11px] tracking-[0.16em] text-upsell-light-blue uppercase">{pilar.resultado}</p></div></article>; })}</div><div className="mt-8 flex justify-center"><CTA /></div></div></section>
    <section id="your-mind-in-gpt" className="border-y border-white/10 bg-white/[0.02] px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle label="YOUR MIND IN GPT" title={<>Build your Digital Mind, <span className="upsell-text-gradient-blue">without programming.</span></>}>How many times have you had to explain what you do, who your audience is, what your goal is, and how you want the text written? You correct the tone, change words, add context, and finally get a reasonable answer. But in the next conversation, everything starts over.</SectionTitle><div className="mx-auto mt-8 max-w-4xl space-y-5 text-center text-base leading-7 text-upsell-text-muted sm:text-lg"><p>Your Mind in GPT shows you how to turn ChatGPT into a personalized intelligence, powered by your identity, knowledge, goals, references, and way of communicating.</p><p>Following a visual, clear, and easy-to-implement process, you learn to build your <span className="font-semibold text-white">Master Profile</span>, create your assistant's instructions, organize your knowledge files, and configure a GPT that works with much more context from the start.</p><p>You don't need to program, understand code, or master technical terms. The guide walks you through every step and provides ready-to-copy structures and prompts to adapt and use.</p></div><div className="mx-auto mt-10 grid max-w-5xl gap-3 sm:grid-cols-2">{beneficiosMente.map(item => <div key={item} className="flex items-center gap-3 rounded-2xl border border-upsell-blue/20 bg-upsell-blue/[0.06] p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-upsell-blue/15 text-upsell-blue"><Check className="h-4 w-4" /></span><p className="text-sm leading-6 text-white/85">{item}</p></div>)}</div><div className="mt-10 flex justify-center"><CTA /></div></div></section>
    <section className="bg-upsell-light-alt px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle light label="THE DIGITAL MIRROR · BONUS" title={<>A new perspective <span className="text-upsell-light-blue">on yourself.</span></>}>What if AI had already noticed something about you that you haven't noticed yet? Use guided prompts to observe patterns in your conversations, recognize strengths, possible blocks, decision-making styles, and opportunities that may be going unnoticed.</SectionTitle><div className="mx-auto mt-8 max-w-4xl text-center text-base leading-7 text-upsell-light-muted sm:text-lg">The Digital Mirror is an AI-guided reflection tool. Its responses are based on information provided by the user and do not represent a diagnosis, therapy, or psychological assessment.</div><div className="mx-auto mt-10 grid max-w-5xl gap-3 sm:grid-cols-2">{beneficiosEspejo.map(item => <div key={item} className="flex items-center gap-3 rounded-2xl border border-upsell-light-border bg-upsell-light-surface p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-upsell-light-blue/10 text-upsell-light-blue"><Check className="h-4 w-4" /></span><p className="text-sm leading-6 text-upsell-light-text/85">{item}</p></div>)}</div><div className="mt-10 flex justify-center"><CTA /></div></div></section>
    <section className="py-14 sm:py-20"><div className="px-5 sm:px-6"><div className="mx-auto max-w-3xl text-center"><div className="upsell-eyebrow mb-4 text-xs tracking-[0.28em] text-upsell-gold uppercase">SEE THE METHOD COME TO LIFE</div><h2 className="text-3xl font-bold text-white sm:text-4xl">It's that simple: anyone can use it,<br className="hidden sm:block" /> <span className="upsell-text-gradient-blue">from anywhere, directly inside ChatGPT.</span></h2></div></div><div className="upsell-marquee-mask mt-10 overflow-hidden"><div className="upsell-marquee flex w-max items-center gap-5 px-5">{[...pilarImagens, ...pilarImagens, ...pilarImagens].map((cover, index) => <CoverCard key={index} cover={cover} name="Expanded Mind Method" />)}</div></div><div className="px-5 sm:px-6"><div className="mx-auto mt-10 max-w-3xl text-center"><div className="upsell-eyebrow mb-4 text-xs tracking-[0.28em] text-upsell-gold uppercase">TESTIMONIALS</div><h3 className="text-2xl font-bold tracking-tight text-white sm:text-3xl">People who have applied the method never use AI the same way again.</h3></div></div><div className="upsell-marquee-mask mt-10 overflow-hidden"><div className="upsell-marquee-reverse flex w-max items-center gap-5 px-5">{[...depoimentos, ...depoimentos].map((item, index) => <TestimonialCard key={index} image={item} index={index % depoimentos.length} />)}</div></div><div className="mt-10 flex justify-center px-5 sm:px-6"><CTA /></div></section>
    <section className="bg-upsell-light-alt px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle light label="IN PRACTICE" title={<>This is what changes <span className="text-upsell-light-blue">from day one.</span></>} /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{resultados.map(({ icon: Icon, title, text }) => <article key={title} className="flex flex-col items-center rounded-[24px] border border-upsell-light-border bg-upsell-light-surface p-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-xl bg-upsell-light-blue/10 text-upsell-light-blue"><Icon className="h-5 w-5" /></div><h3 className="mt-5 text-lg font-bold text-upsell-light-text">{title}</h3><p className="mt-2 text-sm leading-6 text-upsell-light-muted">{text}</p></article>)}</div><div className="mt-10 flex justify-center"><CTA /></div></div></section>
    <section className="py-14 sm:py-20"><div className="px-5 sm:px-6"><SectionTitle label="RESOURCES" title={<>Everything organized for you to <span className="upsell-text-gradient-blue">apply the method.</span></>}>12 ready-to-use resources created to help you apply the method without unnecessary theory:</SectionTitle></div><div className="upsell-marquee-mask mt-12 overflow-hidden"><div className="upsell-marquee-reverse flex w-max gap-3 px-4">{[...recursos, ...recursos].map((resource, index) => <div key={`${resource}-${index}`} className="flex min-w-[230px] items-center gap-3 rounded-2xl bg-white/[0.035] px-5 py-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-upsell-blue/10 text-upsell-blue"><Check className="h-4 w-4" /></div><span className="text-sm font-semibold text-white/85">{resource}</span></div>)}</div></div><div className="mt-10 flex justify-center px-5 sm:px-6"><CTA /></div></section>
    <section className="bg-upsell-light px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><SectionTitle light label="IMAGINE HAVING THIS" title={<>Imagine opening the chat and AI <span className="text-upsell-light-blue">already knows what you're talking about.</span></>}>This is what you'll be able to ask your digital intelligence, without explaining anything again:</SectionTitle><div className="mx-auto mt-8 grid max-w-5xl gap-4">{["Analyze this decision based on my goals, the way I think, and all the context you already know about me.", "I have this idea. Expand it, find the opportunities I'm not seeing, and turn it into an action plan.", "Turn this content into a clear script for my digital avatar and adapt the message for a short video.", "Ask the questions needed to identify which pattern is influencing this decision."].map((prompt, index) => <div key={prompt} className="flex gap-4 rounded-[24px] border border-upsell-light-border bg-upsell-light-surface p-5 sm:p-6"><div className="upsell-eyebrow grid h-10 w-10 shrink-0 place-items-center rounded-full bg-upsell-light-blue/10 text-xs text-upsell-light-blue">0{index + 1}</div><p className="text-sm leading-7 text-upsell-light-text/85 sm:text-base">“{prompt}”</p></div>)}</div><div className="mt-10 flex justify-center"><CTA /></div></div></section>
    <section id="combo" className="relative border-y border-white/10 bg-black/25 px-5 py-14 sm:px-6 sm:py-20"><div className="pointer-events-none absolute left-1/2 top-1/2 h-[520px] w-[820px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-upsell-gold/10 blur-[150px]" /><div className="relative mx-auto max-w-5xl text-center"><span className="upsell-eyebrow inline-flex items-center gap-2 rounded-full border border-upsell-gold/30 bg-upsell-gold/10 px-5 py-2 text-xs tracking-[0.18em] text-upsell-gold uppercase"><Sparkles className="h-4 w-4" /> Limited-Time Promotional Price</span><h2 className="mt-6 text-3xl font-bold tracking-[-0.01em] text-white sm:text-4xl md:text-5xl">The complete Expanded Mind Method<span className="upsell-text-gradient-gold block">All 4 guides in one combo.</span></h2><p className="mx-auto mt-5 max-w-3xl text-base leading-7 text-upsell-text-muted sm:text-lg">You get all four parts of the method to personalize ChatGPT, think with greater clarity, recognize new patterns, and multiply your digital presence.</p><img src={comboCover.url} alt="Expanded Mind Method combo with all 4 guides" className="mx-auto mt-10 w-full max-w-[340px] rounded-[28px] object-cover sm:max-w-md" /><div className="mx-auto mt-10 max-w-3xl overflow-hidden rounded-[32px] border border-upsell-gold/30 bg-white/[0.045] text-left shadow-[0_25px_100px_-40px_rgba(250,204,21,0.35)]"><div className="grid gap-3 p-5 sm:p-8">{comboItens.map(item => <div key={item.nome} className="rounded-2xl border border-white/10 bg-white/[0.04] px-5 py-4"><p className="font-bold text-white">{item.nome} <span className="ml-1 rounded-full bg-upsell-blue/20 px-2 py-0.5 text-[10px] font-bold tracking-wider text-upsell-blue uppercase">{item.etiqueta}</span></p><p className="mt-1 text-xs text-upsell-text-muted">{item.desc}</p></div>)}</div><div className="mx-5 mb-5 rounded-2xl border border-white/10 bg-black/30 p-5 text-center sm:mx-8 sm:mb-8 sm:p-7"><p className="upsell-eyebrow text-xs tracking-[0.22em] text-upsell-gold uppercase">one-time price for the complete combo</p><div className="mt-2 text-4xl font-bold whitespace-nowrap text-upsell-success min-[360px]:text-5xl sm:text-7xl">GET ALL 4 GUIDES FOR $9.99</div><div className="mt-7 flex justify-center"><CTA href="#combo">YES, I WANT THE COMPLETE METHOD</CTA></div><div className="mt-6 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs font-semibold text-white/55"><span className="flex items-center gap-2"><CircleCheck className="h-4 w-4 text-upsell-success" /> Instant access</span><span className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-upsell-success" /> 100% secure payment</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-upsell-success" /> 7-day guarantee</span></div></div></div></div></section>
    <section className="bg-upsell-light-alt px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-4xl text-center"><div className="relative mx-auto grid h-56 w-56 place-items-center rounded-full border-2 border-upsell-success/50 bg-upsell-success/10 text-center sm:h-64 sm:w-64"><div className="absolute inset-3 rounded-full border border-dashed border-upsell-success/40" /><div><BadgeCheck className="mx-auto h-10 w-10 text-upsell-success" /><div className="mt-1 text-6xl font-bold leading-none text-upsell-light-text">7</div><div className="upsell-eyebrow mt-1 text-xs tracking-[0.24em] text-upsell-light-text/70">DAYS</div><div className="mt-2 text-[10px] font-bold tracking-[0.2em] text-upsell-success uppercase">Full Guarantee</div></div></div><div className="mt-10"><div className="upsell-eyebrow text-xs tracking-[0.22em] text-upsell-success uppercase">ZERO RISK FOR YOU</div><h2 className="mt-4 text-4xl font-bold text-upsell-light-text sm:text-5xl">Try it for 7 days. The risk is entirely on us.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-upsell-light-muted sm:text-lg">Come in, apply the method, and see the results for yourself. If within 7 days you decide it's not for you, simply request the guarantee according to the purchase platform's terms.</p></div><div className="mt-10 flex justify-center"><CTA /></div></div></section>
    <section className="bg-upsell-light px-5 py-14 sm:px-6 sm:py-20"><div className="mx-auto max-w-4xl"><SectionTitle light label="FREQUENTLY ASKED QUESTIONS" title="The final step before you begin." /><div className="mt-12 space-y-3">{perguntas.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-upsell-light-border bg-upsell-light-surface p-5 open:border-upsell-light-blue/40"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-upsell-light-text"><span>{question}</span><ChevronDown className="h-5 w-5 shrink-0 text-upsell-light-blue transition group-open:rotate-180" /></summary><p className="mt-4 pr-6 text-sm leading-7 text-upsell-light-muted sm:text-base">{answer}</p></details>)}</div><div className="mt-10 flex justify-center"><CTA /></div></div></section>
    <SalesNotifications />
    <footer className="border-t border-white/10 px-5 py-8 text-center text-xs text-white/35 sm:px-6"><div className="upsell-eyebrow tracking-[0.18em] text-white/55">EXPANDED MIND METHOD™</div><p className="mt-3">Digital product. Results depend on individual application of the method and the tools used.</p><p className="mt-4 text-[10px] text-white/25">© 2026 We Digital Mindset · Created by Soeliz M. Dragaud</p><p className="mt-1 text-[10px] text-white/25"><a href="#privacy-policy" className="underline-offset-2 transition-colors hover:text-white/50">Privacy Policy</a> · <a href="#terms-of-use" className="underline-offset-2 transition-colors hover:text-white/50">Terms of Use</a> · <a href="#contact" className="underline-offset-2 transition-colors hover:text-white/50">Contact</a></p></footer>
  </main>;
}
